/**
 * Product Database — Curated textured hair products.
 *
 * Each product is tagged with hair properties it works best for,
 * which aunty recommends it, and affiliate potential.
 * This is the monetization engine of the app.
 */

import type { AuntyId } from './aunties';
import type { CurlType, Porosity, PrimaryGoal } from '../types';

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: ProductCategory;
  description: string;
  whyItWorks: string; // ingredient science — why this was chosen for their hair
  recommendedBy: AuntyId; // which aunty endorses it
  price: string; // display price
  size: string;
  imageUrl?: string;
  affiliateUrl?: string;

  // Matching criteria
  curlTypes: CurlType[]; // which curl types benefit
  porosity: Porosity[]; // which porosity levels
  goals: PrimaryGoal[]; // which goals it serves
  tags: string[]; // searchable tags

  // Display
  rating: number; // 1-5
  isPremiumPick: boolean;
  isBudgetFriendly: boolean;
  scopeTier: 1 | 2 | 3 | 4;
  priceValue: number;
}

export type ProductCategory =
  | 'cleanser'
  | 'conditioner'
  | 'deep-conditioner'
  | 'leave-in'
  | 'styler'
  | 'oil'
  | 'gel'
  | 'cream'
  | 'protein-treatment'
  | 'scalp-treatment'
  | 'edge-control'
  | 'tool'
  | 'accessory';

export const CATEGORY_LABELS: Record<ProductCategory, string> = {
  cleanser: 'Cleansers',
  conditioner: 'Conditioners',
  'deep-conditioner': 'Deep Conditioners',
  'leave-in': 'Leave-Ins',
  styler: 'Stylers',
  oil: 'Oils & Serums',
  gel: 'Gels',
  cream: 'Creams & Butters',
  'protein-treatment': 'Protein Treatments',
  'scalp-treatment': 'Scalp Treatments',
  'edge-control': 'Edge Control',
  tool: 'Tools',
  accessory: 'Accessories',
};

// ─── Product Catalog ─────────────────────────────────────────────

export const PRODUCTS: Product[] = [
  // ── Cleansers (7) ─────────────────────────────────────────────
  {
    id: 'p-001',
    name: 'Hydrating Cream Cleanser',
    brand: 'SheaMoisture',
    category: 'cleanser',
    description: 'Coconut & Hibiscus co-wash that cleanses without stripping moisture.',
    whyItWorks: 'Sulfate-free so it won\'t strip your natural oils. The coconut oil in this penetrates the hair shaft — one of the only oils that actually does. That\'s why we picked it for your texture.',
    recommendedBy: 'ngozi',
    price: '$11.99',
    size: '13 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=SheaMoisture+Hydrating+Cream+Cleanser',
    imageUrl: 'https://m.media-amazon.com/images/I/71H-D5WQWJL._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'simplify-routine'],
    tags: ['co-wash', 'sulfate-free', 'moisturizing', 'coconut'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 1,
    priceValue: 11.99,
  },
  {
    id: 'p-002',
    name: 'Apple Cider Vinegar Clarifying Shampoo',
    brand: 'dpHUE',
    category: 'cleanser',
    description: 'Gentle clarifying shampoo that removes buildup without over-drying.',
    whyItWorks: 'ACV restores your scalp\'s pH to 4.5-5.5 where textured hair thrives. Removes silicone and mineral buildup without the sulfate damage. We chose this because your curl pattern needs a clean slate without the strip.',
    recommendedBy: 'fatou',
    price: '$35.00',
    size: '8.5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=dpHUE+Apple+Cider+Vinegar+Clarifying+Shampoo',
    imageUrl: 'https://dphue.com/cdn/shop/products/ACV_Rinse.png?v=1656692491',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'scalp-health'],
    tags: ['clarifying', 'ACV', 'buildup', 'gentle'],
    rating: 4.3,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 1,
    priceValue: 35.0,
  },
  {
    id: 'p-003',
    name: 'Black Soap Shampoo',
    brand: 'SheaMoisture',
    category: 'cleanser',
    description: 'African Black Soap deep cleansing shampoo for scalp health.',
    whyItWorks: 'African black soap contains plantain ash and shea — natural antibacterials that clear scalp inflammation without drying your strands. Selected because textured hair needs scalp health as a growth foundation.',
    recommendedBy: 'marcia',
    price: '$10.99',
    size: '13 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=SheaMoisture+Black+Soap+Shampoo',
    imageUrl: 'https://m.media-amazon.com/images/I/719RIvTNd1L._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['scalp-health', 'damage-repair'],
    tags: ['scalp', 'clarifying', 'african-black-soap', 'deep-clean'],
    rating: 4.2,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 1,
    priceValue: 10.99,
  },
  {
    id: 'p-004',
    name: 'Hydration Shampoo',
    brand: 'Pattern Beauty',
    category: 'cleanser',
    description: 'Sulfate-free shampoo with coconut oil and honey for intense hydration.',
    whyItWorks: 'Tracee Ellis Ross formulated this sulfate-free with coconut oil that penetrates the cortex and honey as a humectant. The combination cleanses while depositing moisture — the opposite of what most shampoos do to textured hair.',
    recommendedBy: 'ngozi',
    price: '$25.00',
    size: '9.8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Pattern+Beauty+Hydration+Shampoo',
    imageUrl: 'https://patternbeauty.com/cdn/shop/files/hydration_shampoo_2000x2000_72dpicopy_1.jpg?v=1761948463',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'definition'],
    tags: ['sulfate-free', 'hydrating', 'pattern-beauty', 'tracee'],
    rating: 4.5,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 1,
    priceValue: 25.0,
  },
  {
    id: 'p-005',
    name: 'Coconut CoWash Cleansing Conditioner',
    brand: 'As I Am',
    category: 'cleanser',
    description: 'Conditioning cleanser with coconut and tangerine that defines while washing.',
    whyItWorks: 'Cetyl and cetearyl alcohol create a true conditioning cleanse — they have enough surfactant action to lift dirt but enough emollient to leave moisture behind. The co-wash that put co-washing on the map.',
    recommendedBy: 'denise',
    price: '$8.99',
    size: '16 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=As+I+Am+Don%5C',
    imageUrl: 'https://asiamnaturally.com/cdn/shop/products/02.AsIAmClassic_CoconutCowashsquare.jpg?v=1678475184',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'simplify-routine'],
    tags: ['co-wash', 'coconut', 'conditioning', 'budget'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 1,
    priceValue: 8.99,
  },
  {
    id: 'p-006',
    name: 'Don\'t Despair, Repair! Super Moisture Shampoo',
    brand: 'Briogeo',
    category: 'cleanser',
    description: 'Rosehip oil and biotin repair shampoo that cleanses without stripping.',
    whyItWorks: 'Rosehip oil is rich in linoleic acid which repairs the lipid layer of damaged hair. Biotin strengthens keratin bonds. Algae extract provides slip. This cleans without punishing — chosen for compromised textures.',
    recommendedBy: 'salma',
    price: '$28.00',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Briogeo+Don%27t+Despair%2C+Repair%21+Super+Moisture+Shampoo',
    imageUrl: 'https://m.media-amazon.com/images/I/21N53o22VGL._SL500_.jpg',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['damage-repair', 'moisture'],
    tags: ['repair', 'rosehip', 'biotin', 'gentle'],
    rating: 4.3,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 1,
    priceValue: 28.0,
  },
  {
    id: 'p-007',
    name: 'Guava Hydrating Shampoo',
    brand: 'Ceremonia',
    category: 'cleanser',
    description: 'Guava extract shampoo that protects against UV and oxidative damage.',
    whyItWorks: 'Guava extract is rich in lycopene — a powerful antioxidant that neutralizes UV and pollution damage at the cuticle level. Latinx-owned brand that draws on traditional Caribbean hair science.',
    recommendedBy: 'carmen',
    price: '$26.00',
    size: '12 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Ceremonia+Guava+Hydrating+Shampoo',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0414/8301/0212/files/Ceremonia_MiniChampuGuava_4x5_Cream.webp',
    curlTypes: ['2a', '2b', '2c', '3a', '3b'],
    porosity: ['low', 'normal'],
    goals: ['damage-repair', 'scalp-health'],
    tags: ['guava', 'antioxidant', 'UV-protection', 'latinx-owned'],
    rating: 4.4,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 1,
    priceValue: 26.0,
  },

  // ── Deep Conditioners (5) ─────────────────────────────────────
  {
    id: 'p-011',
    name: 'Cholesterol Hair Conditioning Cream',
    brand: 'Queen Helene',
    category: 'deep-conditioner',
    description: 'Classic deep conditioner that softens and strengthens textured hair.',
    whyItWorks: 'Cholesterol-based conditioners mimic your hair\'s natural lipid layer — they fill gaps in damaged cuticles. This formula softens without protein overload, making it safe for weekly use on textured hair.',
    recommendedBy: 'denise',
    price: '$6.99',
    size: '15 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Queen+Helene+Intensive+Conditioner',
    imageUrl: 'https://m.media-amazon.com/images/I/71JpGpPWAEL._SL500_.jpg',
    curlTypes: ['3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'damage-repair', 'simplify-routine'],
    tags: ['deep-condition', 'classic', 'softening', 'budget'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 6.99,
  },
  {
    id: 'p-013',
    name: 'Intensive Conditioner',
    brand: 'Pattern Beauty',
    category: 'deep-conditioner',
    description: 'Heavy-duty slip conditioner for detangling coils with safflower, shea, and avocado.',
    whyItWorks: 'Safflower oil is 78% linoleic acid — it rebuilds the lipid barrier on high-porosity strands. Combined with shea and avocado for slip, this was formulated by Tracee Ellis Ross specifically for 3c-4c textures that need serious detangling power.',
    recommendedBy: 'ngozi',
    price: '$25.00',
    size: '13 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Pattern+Beauty+Intensive+Conditioner',
    imageUrl: 'https://patternbeauty.com/cdn/shop/files/RT_IntensiveConditioner13oz_1_copy_5ca345df-63c4-4e90-bd25-47dba7e49979.jpg?v=1761948757',
    curlTypes: ['3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'definition'],
    tags: ['intensive', 'detangle', 'slip', 'pattern-beauty', 'coily'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 25.0,
  },
  {
    id: 'p-014',
    name: 'Don\'t Despair, Repair! Deep Conditioning Mask',
    brand: 'Briogeo',
    category: 'deep-conditioner',
    description: 'Bond-rebuilding mask with hydrolyzed keratin, rosehip oil, and algae.',
    whyItWorks: 'Hydrolyzed keratin is small enough to enter the cortex and fill structural gaps. Rosehip oil\'s vitamin A accelerates cell turnover. Algae provides amino acids that mirror hair\'s own protein structure. Rebuilds what heat and chemicals broke down.',
    recommendedBy: 'amara',
    price: '$38.00',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Briogeo+Honey+Miracle+Hair+Mask',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0905/3204/files/01_DDR-Mask_On-White.png?v=1778615878',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a'],
    porosity: ['low', 'normal', 'high'],
    goals: ['damage-repair', 'moisture'],
    tags: ['repair', 'keratin', 'mask', 'bond-building'],
    rating: 4.7,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 38.0,
  },
  {
    id: 'p-015',
    name: 'Honey Miracle Hair Mask',
    brand: 'TGIN',
    category: 'deep-conditioner',
    description: 'Raw honey, jojoba, and olive oil triple-moisture deep treatment.',
    whyItWorks: 'Raw honey is a humectant AND an emollient — it pulls moisture in AND seals it. Jojoba mimics your hair\'s natural sebum so it absorbs without residue. Olive oil\'s oleic acid fills cuticle gaps. A triple-moisture system at a budget price.',
    recommendedBy: 'denise',
    price: '$14.99',
    size: '12 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=CurlSmith+Double+Cream+Deep+Quencher',
    imageUrl: 'https://tginatural.com/cdn/shop/files/Honey_Miracle_December_2025_2.png?v=1765391878&width=1024',
    curlTypes: ['3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'damage-repair'],
    tags: ['honey', 'mask', 'moisture', 'jojoba', 'olive'],
    rating: 4.6,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 14.99,
  },
  {
    id: 'p-016',
    name: 'Double Cream Deep Quencher',
    brand: 'CurlSmith',
    category: 'deep-conditioner',
    description: 'Dual-phase emulsion with avocado butter and flaxseed for deep quenching.',
    whyItWorks: 'Dual-phase means water-soluble humectants work alongside oil-soluble emollients — it hydrates the cortex AND seals the cuticle in one step. Avocado butter penetrates deeper than most plant butters due to its small molecular size.',
    recommendedBy: 'fatou',
    price: '$27.99',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=CurlSmith+Double+Cream+Deep+Quencher',
    imageUrl: 'https://curlsmith.com/cdn/shop/files/Double-Cream-Deep-Quencher_8floz_Front_2000x2000_29527595-4f52-47ed-a2ca-2290c918fba7.jpg?v=1755506234',
    curlTypes: ['2c', '3a', '3b', '3c', '4a', '4b'],
    porosity: ['low', 'normal', 'high'],
    goals: ['moisture', 'definition'],
    tags: ['deep-quench', 'avocado', 'flaxseed', 'dual-phase'],
    rating: 4.5,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 27.99,
  },

  // ── Leave-Ins (6) ─────────────────────────────────────────────
  {
    id: 'p-020',
    name: 'Knot Today Leave-In Conditioner',
    brand: 'Kinky-Curly',
    category: 'leave-in',
    description: 'Lightweight detangling leave-in that defines without weighing down.',
    whyItWorks: 'Organic marshmallow root extract adds serious slip, so strands glide past each other instead of snagging. No silicones. Selected because textured hair needs gentle detangling that helps protect against breakage.',
    recommendedBy: 'fatou',
    price: '$14.99',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Kinky-Curly+Knot+Today+Leave-In+Conditioner',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0489/0371/7029/products/Kinky-CurlyKnotToday.png',
    curlTypes: ['3a', '3b', '3c', '4a'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'simplify-routine'],
    tags: ['leave-in', 'detangle', 'lightweight', 'slip'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 14.99,
  },
  {
    id: 'p-021',
    name: 'Quench Leave-In Conditioning Cream',
    brand: 'Aunt Jackie\'s',
    category: 'leave-in',
    description: 'Rich moisture leave-in for thick, coily hair that needs extra hydration.',
    whyItWorks: 'Shea butter and olive oil are heavy emollients that coat high-porosity strands and slow moisture loss. This stays on coily hair where lighter leave-ins evaporate in hours.',
    recommendedBy: 'ngozi',
    price: '$8.99',
    size: '12 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Pattern+Beauty+Leave-In+Conditioner',
    imageUrl: 'https://m.media-amazon.com/images/I/71WjEsjddbL._SL500_.jpg',
    curlTypes: ['4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'growth'],
    tags: ['leave-in', 'cream', 'moisture', 'thick-hair', 'coily'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 8.99,
  },
  {
    id: 'p-022',
    name: 'Leave-In Conditioner',
    brand: 'Pattern Beauty',
    category: 'leave-in',
    description: 'Heavyweight leave-in with coconut and shea for intense moisture and slip.',
    whyItWorks: 'Available in light, medium, and heavy weights because not every curl is the same. Coconut oil penetrates the shaft while shea seals the cuticle. Formulated by Tracee Ellis Ross for the specific needs of 3a-4c textures.',
    recommendedBy: 'ngozi',
    price: '$25.00',
    size: '9.8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Bread+Beauty+Supply+Hair-Oil+Everyday+Gloss',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0149/4794/2500/files/LeaveInConditioner_1.75oz_-1-Front-00017_onpeach.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'definition', 'simplify-routine'],
    tags: ['leave-in', 'pattern-beauty', 'slip', 'tracee', 'coconut'],
    rating: 4.5,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 25.0,
  },
  {
    id: 'p-023',
    name: 'Hair-Oil Everyday Gloss',
    brand: 'Bread Beauty Supply',
    category: 'leave-in',
    description: 'Lightweight oil-cream hybrid with castor, argan, and sweet almond.',
    whyItWorks: 'Castor oil\'s ricinoleic acid strengthens while argan\'s linoleic acid repairs. Sweet almond rounds it out with vitamin E for oxidative protection. This oil knows when to stop — it gives shine without the grease.',
    recommendedBy: 'salma',
    price: '$24.00',
    size: '4.4 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Camille+Rose+Curl+Love+Moisture+Milk',
    imageUrl: 'https://breadbeautysupply.com/cdn/shop/files/Untitled_design_bd69b3d2-fbdd-4c8e-89c2-92cbd30c6714.png?v=1723637619',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['moisture', 'simplify-routine'],
    tags: ['oil', 'lightweight', 'shine', 'castor', 'argan'],
    rating: 4.3,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 24.0,
  },
  {
    id: 'p-024',
    name: 'Curl Love Moisture Milk',
    brand: 'Camille Rose',
    category: 'leave-in',
    description: 'Rice milk protein and castor oil leave-in for moisture-protein balance.',
    whyItWorks: 'Rice protein strengthens without stiffness — its amino acid profile is lighter than keratin-based proteins. Castor oil provides ricinoleic acid for growth. Macadamia seals it all in. Rice water has been feeding Caribbean and Asian hair for generations.',
    recommendedBy: 'marcia',
    price: '$14.99',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=It%5C+Miracle+Leave-In+Product',
    imageUrl: 'https://www.camillerose.com/cdn/shop/files/ProductCard_Signature_LeaveinConditioner.webp?v=1772795367',
    curlTypes: ['3a', '3b', '3c', '4a', '4b'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'growth'],
    tags: ['rice-milk', 'protein', 'moisture', 'castor', 'leave-in'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 14.99,
  },
  {
    id: 'p-025',
    name: 'Miracle Leave-In Product',
    brand: 'It\'s a 10',
    category: 'leave-in',
    description: 'Multi-benefit leave-in that detangles, protects heat to 450F, and prevents split ends.',
    whyItWorks: 'Ten active benefits in one product: heat protection (silicone-based shield to 450F), detangling (quaternary compounds reduce friction), split end prevention (amino acids temporarily bond split ends), plus UV protection. One product that does many things well.',
    recommendedBy: 'fatou',
    price: '$19.99',
    size: '10 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Kinky-Curly+Curling+Custard',
    imageUrl: 'https://itsa10haircare.com/cdn/shop/files/Conditioning_Leave_in_4oz.jpg?v=1763485416',
    curlTypes: ['2a', '2b', '2c', '3a', '3b'],
    porosity: ['low', 'normal'],
    goals: ['damage-repair', 'simplify-routine'],
    tags: ['multi-benefit', 'heat-protection', 'detangle', 'leave-in'],
    rating: 4.4,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 19.99,
  },

  // ── Gels (7) ──────────────────────────────────────────────────
  {
    id: 'p-030',
    name: 'Curling Custard',
    brand: 'Kinky-Curly',
    category: 'gel',
    description: 'Organic gel that defines curls with zero crunch or flaking.',
    whyItWorks: 'Organic aloe and agave create a flexible cast that defines without crunch. No polyquats or PVP that cause flaking on textured hair. Chosen because your curl pattern needs hold that moves.',
    recommendedBy: 'carmen',
    price: '$17.99',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Aunt+Jackie%5C+Flaxseed+Gel',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0489/0371/7029/products/Kinky-CurlyCurlingCustardWebcopy.png',
    curlTypes: ['3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'simplify-routine'],
    tags: ['gel', 'definition', 'organic', 'no-crunch', 'wash-and-go'],
    rating: 4.6,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 17.99,
  },
  {
    id: 'p-031',
    name: 'Flaxseed Gel',
    brand: 'Aunt Jackie\'s',
    category: 'gel',
    description: 'Natural flaxseed gel for soft hold and curl definition.',
    whyItWorks: 'Flaxseed mucilage is a natural polymer — it forms a gel film that defines curls while adding omega-3 fatty acids that strengthen the strand. No synthetic hold agents. Works across all porosity levels.',
    recommendedBy: 'carmen',
    price: '$8.99',
    size: '15 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Eco+Styler+Olive+Oil+Styling+Gel',
    imageUrl: 'https://m.media-amazon.com/images/I/71iC2+KFbkL._SL500_.jpg',
    curlTypes: ['2c', '3a', '3b', '3c', '4a'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition', 'simplify-routine'],
    tags: ['gel', 'flaxseed', 'natural', 'soft-hold', 'definition'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 8.99,
  },
  {
    id: 'p-033',
    name: 'Olive Oil Styling Gel',
    brand: 'Eco Styler',
    category: 'gel',
    description: 'Maximum hold gel with olive oil that defines without drying.',
    whyItWorks: 'PVP/VA copolymer provides maximum hold while olive oil\'s oleic acid prevents the drying effect most gels cause. At under $5 for 16 oz, it delivers professional results at drugstore prices. A staple for decades.',
    recommendedBy: 'denise',
    price: '$4.99',
    size: '16 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Uncle+Funky%5C+Curly+Magic+Curl+Stimulator',
    imageUrl: 'https://m.media-amazon.com/images/I/71z5SXZ4ZLL._SL500_.jpg',
    curlTypes: ['2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition', 'simplify-routine'],
    tags: ['gel', 'maximum-hold', 'olive-oil', 'budget', 'classic'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 4.99,
  },
  {
    id: 'p-034',
    name: 'Curly Magic Curl Stimulator',
    brand: 'Uncle Funky\'s Daughter',
    category: 'gel',
    description: 'Organic aloe, chamomile, and nettle gel that defines without crunch or flaking.',
    whyItWorks: 'Organic aloe vera provides the hold matrix while chamomile and nettle extracts soothe the scalp and add shine. No polyquats means zero flaking. The name has personality, and so will your curls.',
    recommendedBy: 'carmen',
    price: '$18.99',
    size: '12 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Aussie+Instant+Freeze+Sculpting+Gel',
    imageUrl: 'https://m.media-amazon.com/images/I/81WGACPbPLL._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a'],
    porosity: ['low', 'normal'],
    goals: ['definition'],
    tags: ['gel', 'organic', 'aloe', 'chamomile', 'no-flake'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 18.99,
  },
  {
    id: 'p-036',
    name: 'Instant Freeze Sculpting Gel',
    brand: 'Aussie',
    category: 'gel',
    description: 'Maximum hold gel with jojoba and sea kelp at extreme value pricing.',
    whyItWorks: 'Jojoba seed oil mimics sebum so it moisturizes while the polymer system holds. Sea kelp provides minerals that strengthen the cuticle. Under four dollars and it holds a wash-and-go like nobody\'s business.',
    recommendedBy: 'denise',
    price: '$3.99',
    size: '7 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Boucleme+Curl+Defining+Gel',
    imageUrl: 'https://m.media-amazon.com/images/I/61pRRPUSoxL._SL500_.jpg',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'simplify-routine'],
    tags: ['gel', 'maximum-hold', 'budget', 'jojoba', 'sea-kelp'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 3.99,
  },
  {
    id: 'p-038',
    name: 'Curl Defining Gel',
    brand: 'Boucleme',
    category: 'gel',
    description: 'Virgin coconut, flaxseed, and aloe gel with light hold. Vegan, UK-made.',
    whyItWorks: 'Virgin coconut oil is the only oil proven to penetrate the hair shaft. Flaxseed mucilage provides flexible hold. Aloe vera seals moisture. Vegan and made in London with ingredients the earth provides — light, clean, honest definition.',
    recommendedBy: 'salma',
    price: '$22.00',
    size: '10.1 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Cantu+Twist+Defining+Cream',
    imageUrl: 'https://m.media-amazon.com/images/I/613YdmsnIqL._SL500_.jpg',
    curlTypes: ['2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'simplify-routine'],
    tags: ['gel', 'vegan', 'coconut', 'flaxseed', 'UK', 'clean'],
    rating: 4.4,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 22.0,
  },

  // ── Creams & Stylers (1) ──────────────────────────────────────
  {
    id: 'p-032',
    name: 'Twist Defining Cream',
    brand: 'Cantu',
    category: 'cream',
    description: 'Shea butter cream for twist-outs and braid-outs with lasting moisture.',
    whyItWorks: 'Shea butter\'s stearic acid fills gaps in the cuticle, reducing frizz and locking twist definition for 3-5 days. We chose this for coily patterns that need a cream heavy enough to hold a set.',
    recommendedBy: 'denise',
    price: '$5.99',
    size: '12 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Tropic+Isle+Living+Jamaican+Black+Castor+Oil',
    imageUrl: 'https://m.media-amazon.com/images/I/711OvD9RJ0L._SL500_.jpg',
    curlTypes: ['3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['definition', 'moisture'],
    tags: ['cream', 'twist-out', 'shea-butter', 'protective-style'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 5.99,
  },

  // ── Oils & Serums (7) ─────────────────────────────────────────
  {
    id: 'p-040',
    name: 'Jamaican Black Castor Oil',
    brand: 'Tropic Isle Living',
    category: 'oil',
    description: 'Pure JBCO for scalp massage, edges, and growth stimulation.',
    whyItWorks: 'A rich, traditional oil prized for coating and sealing the strand. Its thick, ricinoleic-acid base helps lock moisture into thirsty coily hair and is a longtime favorite for sealing ends and edges.',
    recommendedBy: 'marcia',
    price: '$9.99',
    size: '4 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Josie+Maran+Pure+Argan+Oil',
    imageUrl: 'https://cdn.shopify.com/s/files/1/2801/1342/files/JB12X.jpg',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['growth', 'scalp-health', 'damage-repair'],
    tags: ['oil', 'JBCO', 'growth', 'scalp', 'edges', 'massage'],
    rating: 4.8,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 9.99,
  },
  {
    id: 'p-041',
    name: 'Pure Argan Oil',
    brand: 'Josie Maran',
    category: 'oil',
    description: 'Lightweight argan oil that seals moisture and adds shine without weight.',
    whyItWorks: 'Argan is 80% unsaturated fatty acids — it penetrates without coating. Vitamin E repairs oxidative damage. Chosen for low-porosity hair because it\'s light enough to absorb where heavier oils can\'t.',
    recommendedBy: 'salma',
    price: '$49.00',
    size: '1.7 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Mielle+Organics+Rosemary+Mint+Scalp+Oil',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1670/4453/files/100-percent-pure-organic-argan-oil-15mL-2048x2048_523483c4-aa86-42c7-9646-c6413353a1c0.png',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['moisture', 'definition', 'simplify-routine'],
    tags: ['oil', 'argan', 'lightweight', 'shine', 'sealing', 'moroccan'],
    rating: 4.7,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 49.0,
  },
  {
    id: 'p-042',
    name: 'Rosemary Mint Scalp Oil',
    brand: 'Mielle Organics',
    category: 'oil',
    description: 'Stimulating scalp oil with rosemary and biotin for growth.',
    whyItWorks: 'Rosemary and mint awaken the scalp for a fresh, tingly clean that fans swear by. A lightweight, invigorating oil that conditions the scalp and strands without heaviness.',
    recommendedBy: 'marcia',
    price: '$9.99',
    size: '2 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Olaplex+No.7+Bonding+Oil',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0763/8199/files/rm-quencher-front.jpg',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['growth', 'scalp-health'],
    tags: ['oil', 'rosemary', 'mint', 'growth', 'scalp', 'stimulating'],
    rating: 4.8,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 9.99,
  },
  {
    id: 'p-043',
    name: 'No.7 Bonding Oil',
    brand: 'Olaplex',
    category: 'oil',
    description: 'Bond-repairing oil with heat protection to 450F and visible shine.',
    whyItWorks: 'Built around Olaplex\'s patented bond-building technology and designed to help repair the look and feel of damaged, over-processed hair. Adds shine and smoothness with heat protection up to 450F.',
    recommendedBy: 'amara',
    price: '$30.00',
    size: '1 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Melanin+Haircare+Multi-Use+Softening+Leave-In+Conditioner',
    imageUrl: 'https://olaplex.com/cdn/shop/files/ClosetoFinal_Transparent_No7-Bottle_30ml_Product-Packshot_WS_FRONT_FPO_0040_MAIN.png?v=1762285968',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['damage-repair', 'definition'],
    tags: ['oil', 'bond-repair', 'olaplex', 'heat-protection', 'shine'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 30.0,
  },
  {
    id: 'p-044',
    name: 'Multi-Use Softening Leave-In Conditioner',
    brand: 'Melanin Haircare',
    category: 'oil',
    description: 'African baobab and honey oil-cream hybrid by Naptural85.',
    whyItWorks: 'Baobab oil is rich in vitamins A, D, and E — a rare combination that repairs, moisturizes, and protects simultaneously. Created by Whitney White (Naptural85) from her own natural hair journey. When someone walks the walk, you trust the product.',
    recommendedBy: 'marcia',
    price: '$16.00',
    size: '8.5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Eden+BodyWorks+Jojoba+Monoi+All+Natural+Hair+Oil',
    imageUrl: 'https://www.melaninhaircareevents.com/cdn/shop/files/01_Multi-UseSofteningLeaveInConditioner_NewOunces_5.jpg?v=1741054928',
    curlTypes: ['3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'growth'],
    tags: ['oil', 'baobab', 'honey', 'black-owned', 'naptural85'],
    rating: 4.5,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 16.0,
  },
  {
    id: 'p-045',
    name: 'Jojoba Monoi All Natural Hair Oil',
    brand: 'Eden BodyWorks',
    category: 'oil',
    description: 'Jojoba and monoi oil blend that mimics natural sebum for balanced moisture.',
    whyItWorks: 'Jojoba is molecularly identical to human sebum — your hair literally can\'t tell the difference. Monoi (gardenia-infused coconut) seals with medium weight. The oil that tricks your hair into thinking it made it itself.',
    recommendedBy: 'denise',
    price: '$6.99',
    size: '4 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Flora+%26+Curl+Sweet+Hibiscus+Curl+Activating+Lotion',
    imageUrl: 'https://edenbodyworks.com/cdn/shop/files/CoconutShea-Texture-8158-web_a1af6e96-51d0-4aef-afd8-2c9067c12c7f.jpg?v=1727201592',
    curlTypes: ['2c', '3a', '3b', '3c', '4a', '4b'],
    porosity: ['low', 'normal', 'high'],
    goals: ['moisture', 'simplify-routine'],
    tags: ['oil', 'jojoba', 'monoi', 'lightweight', 'natural', 'budget'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 6.99,
  },
  {
    id: 'p-046',
    name: 'Sweet Hibiscus Curl Activating Lotion',
    brand: 'Flora & Curl',
    category: 'oil',
    description: 'Hibiscus extract and flaxseed curl activator with amino acids.',
    whyItWorks: 'Hibiscus is rich in amino acids that strengthen the keratin structure and AHAs that gently exfoliate the cuticle for better absorption. Flaxseed provides flexible hold. Used in African and Asian hair care for centuries — this formula respects that heritage.',
    recommendedBy: 'fatou',
    price: '$26.00',
    size: '10.1 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Aphogee+Two+Step+Protein+Treatment',
    imageUrl: 'https://m.media-amazon.com/images/I/61A9nAUYZvL._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a'],
    porosity: ['normal', 'high'],
    goals: ['definition', 'moisture'],
    tags: ['hibiscus', 'flaxseed', 'curl-activator', 'UK', 'amino-acids'],
    rating: 4.5,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 26.0,
  },

  // ── Protein Treatments (5) ────────────────────────────────────
  {
    id: 'p-050',
    name: 'Two Step Protein Treatment',
    brand: 'Aphogee',
    category: 'protein-treatment',
    description: 'Professional-strength protein treatment for severely damaged hair.',
    whyItWorks: 'Hydrolyzed keratin proteins are small enough to enter the cortex and rebuild internal bonds. This is the gold standard for structural repair — chosen when elasticity is compromised from heat or chemical damage.',
    recommendedBy: 'amara',
    price: '$14.99',
    size: '4 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Olaplex+No.3+Hair+Perfector',
    imageUrl: 'https://aphogee.com/cdn/shop/files/WhatsApp_Image_2025-04-22_at_10.25.55_AM.png?v=1745469543',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['damage-repair', 'growth'],
    tags: ['protein', 'repair', 'professional', 'breakage', 'strength'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 14.99,
  },
  {
    id: 'p-051',
    name: 'No.3 Hair Perfector',
    brand: 'Olaplex',
    category: 'protein-treatment',
    description: 'Patented bond-repair treatment that reconnects broken disulfide bonds at the molecular level.',
    whyItWorks: 'Olaplex\'s patented bond-building treatment helps improve the strength, look, and feel of damaged, over-processed hair. A weekly reset that leaves strands smoother and more resilient.',
    recommendedBy: 'amara',
    price: '$30.00',
    size: '3.3 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=CurlSmith+Bond+Curl+Rehab+Salve',
    imageUrl: 'https://olaplex.com/cdn/shop/files/2025_No3PLUS_100ml_Product_Packshot_01_GBL_1440x1440_a2cbc609-6363-49e1-b2d2-7acd8a72672f.png?v=1771621517',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['damage-repair', 'transition'],
    tags: ['bond-repair', 'olaplex', 'molecular', 'disulfide', 'treatment'],
    rating: 4.7,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 30.0,
  },
  {
    id: 'p-052',
    name: 'Bond Curl Rehab Salve',
    brand: 'CurlSmith',
    category: 'protein-treatment',
    description: 'Hydrolyzed pea protein and ceramides that rebuild and seal the cuticle.',
    whyItWorks: 'Hydrolyzed pea protein provides amino acids small enough to penetrate the cortex while ceramides seal the cuticle from outside. Your hair gets rebuilt from both directions — inside out AND outside in.',
    recommendedBy: 'amara',
    price: '$30.99',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Mielle+Organics+Babassu+Oil+%26+Mint+Deep+Conditioner',
    imageUrl: 'https://curlsmith.com/cdn/shop/files/Bond-Curl-Rehab-Salve_8floz_Front_2000x2000_2f18e69f-fb6d-4d92-9573-e49eab94865b.jpg?v=1763792409',
    curlTypes: ['2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['damage-repair', 'moisture'],
    tags: ['bond-repair', 'protein', 'ceramides', 'pea-protein', 'rehab'],
    rating: 4.5,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 30.99,
  },
  {
    id: 'p-053',
    name: 'Babassu Oil & Mint Deep Conditioner',
    brand: 'Mielle Organics',
    category: 'protein-treatment',
    description: 'Babassu protein and peppermint treatment that strengthens while stimulating growth.',
    whyItWorks: 'Babassu oil\'s lauric acid provides protein-like reinforcement while peppermint\'s menthol increases blood flow to follicles. Growth stimulation from the scalp while strengthening from the strand. Protein from both ends.',
    recommendedBy: 'marcia',
    price: '$13.99',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=SheaMoisture+Manuka+Honey+%26+Yogurt+Hydrate+%2B+Repair+Protein+Treatment',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0763/8199/files/Packshot_Mielle_SHAseal_BabMint_DeepCond_8oz_En_80835620_2048px.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['damage-repair', 'growth'],
    tags: ['protein', 'babassu', 'mint', 'growth', 'stimulating'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 13.99,
  },
  {
    id: 'p-054',
    name: 'Manuka Honey & Yogurt Hydrate + Repair Protein Treatment',
    brand: 'SheaMoisture',
    category: 'protein-treatment',
    description: 'Yogurt protein and manuka honey treatment that heals high-porosity damage.',
    whyItWorks: 'Yogurt contains keratin-adjacent proteins that temporarily fill structural gaps in the cortex. Manuka honey\'s methylglyoxal is antibacterial AND a powerful humectant. Protein that doesn\'t make your hair stiff — your grandmother would approve.',
    recommendedBy: 'ngozi',
    price: '$12.99',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=TGIN+Tea+Tree+Scalp+Treatment',
    imageUrl: 'https://m.media-amazon.com/images/I/61OAGGgT3cL._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['damage-repair', 'moisture'],
    tags: ['protein', 'manuka', 'yogurt', 'repair', 'hydrate'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 12.99,
  },

  // ── Scalp Treatments (5) ──────────────────────────────────────
  {
    id: 'p-060',
    name: 'Tea Tree Scalp Treatment',
    brand: 'TGIN',
    category: 'scalp-treatment',
    description: 'Soothing tea tree and argan oil treatment for itchy, flaky scalps.',
    whyItWorks: 'Tea tree oil\'s terpinen-4-ol is antifungal and anti-inflammatory — targets the root cause of dandruff, not just symptoms. Argan soothes without clogging follicles. Selected for scalp conditions common in textured hair.',
    recommendedBy: 'salma',
    price: '$14.99',
    size: '4 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Briogeo+Scalp+Revival+Charcoal+%2B+Coconut+Oil+Micro-Exfoliating+Shampoo',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0716/9540/1252/files/Tea_Tree_Feb_2026.png',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['scalp-health'],
    tags: ['scalp', 'tea-tree', 'soothing', 'anti-itch', 'treatment'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 14.99,
  },
  {
    id: 'p-061',
    name: 'Scalp Revival Charcoal + Coconut Oil Micro-Exfoliating Shampoo',
    brand: 'Briogeo',
    category: 'scalp-treatment',
    description: 'Binchotan charcoal draws out impurities while coconut oil replenishes.',
    whyItWorks: 'Binchotan charcoal has 10x the surface area of regular charcoal — it adsorbs sebum, product buildup, and pollution particulates from the scalp. Coconut oil immediately replenishes what was removed. A fresh start without harshness.',
    recommendedBy: 'salma',
    price: '$42.00',
    size: '6.5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=TPH+by+Taraji+Master+Cleanse+Scalp+Treatment',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0905/3204/products/sr-shampoo-full-size-1.jpg?v=1762439554',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['scalp-health'],
    tags: ['scalp', 'charcoal', 'exfoliating', 'detox', 'coconut'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 42.0,
  },
  {
    id: 'p-062',
    name: 'Master Cleanse Scalp Treatment',
    brand: 'TPH by Taraji',
    category: 'scalp-treatment',
    description: 'Witch hazel, tea tree, and piroctone olamine anti-fungal scalp treatment.',
    whyItWorks: 'A clarifying scalp treatment that helps wash away buildup and flakes for a fresher, cleaner-feeling scalp. Witch hazel and tea tree leave the scalp feeling balanced and refreshed. Taraji knows what it\'s like to have cameras on your hairline.',
    recommendedBy: 'marcia',
    price: '$12.99',
    size: '4 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Sienna+Naturals+H.A.P.I.+Shampoo',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0284/3790/5513/products/MasterCleanseScalpTreatmentWash8oz-front.png',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['scalp-health'],
    tags: ['scalp', 'anti-fungal', 'witch-hazel', 'tea-tree', 'taraji'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 4,
    priceValue: 12.99,
  },
  {
    id: 'p-063',
    name: 'H.A.P.I. Shampoo',
    brand: 'Sienna Naturals',
    category: 'scalp-treatment',
    description: 'AHA scalp exfoliation with glycolic acid that removes buildup gently.',
    whyItWorks: 'Glycolic acid chemically dissolves dead skin cells and product buildup on the scalp without the mechanical damage of physical scrubs. AHA exfoliation is precise and effective — the buildup doesn\'t stand a chance. Black-owned.',
    recommendedBy: 'fatou',
    price: '$25.00',
    size: '10 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Sunday+II+Sunday+Edge+Flourish+Serum',
    imageUrl: 'https://www.siennanaturals.com/cdn/shop/products/HAPISHAMPOO_600x600.png?v=1762458496',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['scalp-health', 'growth'],
    tags: ['scalp', 'AHA', 'glycolic', 'exfoliation', 'black-owned'],
    rating: 4.4,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 25.0,
  },
  {
    id: 'p-064',
    name: 'Edge Flourish Serum',
    brand: 'Sunday II Sunday',
    category: 'scalp-treatment',
    description: 'Peptides and caffeine serum targeting thinning edges and hairline.',
    whyItWorks: 'A lightweight serum that conditions the hairline and edges, leaving them soft, smooth, and cared-for. Peptides and caffeine in a nourishing base for the most delicate hairs. Your edges are precious — treat them gently.',
    recommendedBy: 'marcia',
    price: '$24.00',
    size: '1 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Pattern+Beauty+Edge+Control',
    imageUrl: 'https://m.media-amazon.com/images/I/516NAI9LhML._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['growth', 'scalp-health'],
    tags: ['edges', 'peptides', 'caffeine', 'growth', 'hairline', 'black-owned'],
    rating: 4.3,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 24.0,
  },

  // ── Edge Control (6) ──────────────────────────────────────────
  {
    id: 'p-080',
    name: 'Edge Control',
    brand: 'Pattern Beauty',
    category: 'edge-control',
    description: 'Strong hold edge control with castor oil that nourishes while holding.',
    whyItWorks: 'Castor oil\'s ricinoleic acid strengthens the delicate edge hairs while the polymer system provides all-day hold without flaking. Your edges should be laid AND healthy — Tracee wouldn\'t have it any other way.',
    recommendedBy: 'denise',
    price: '$12.50',
    size: '2 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Mielle+Organics+Rosemary+Mint+Strengthening+Edge+Gel',
    imageUrl: 'https://patternbeauty.com/cdn/shop/files/stylers-sized_0000_Layer9_copy.jpg?v=1761887286',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['definition'],
    tags: ['edge-control', 'castor', 'hold', 'pattern-beauty', 'edges'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 12.5,
  },
  {
    id: 'p-081',
    name: 'Rosemary Mint Strengthening Edge Gel',
    brand: 'Mielle Organics',
    category: 'edge-control',
    description: 'Rosemary and biotin edge gel that holds and promotes edge growth.',
    whyItWorks: 'Rosemary stimulates blood flow to the hairline (clinically proven as effective as minoxidil). Biotin reinforces keratin bonds. This holds your edges AND grows them at the same time — that\'s not a compromise, that\'s a win-win.',
    recommendedBy: 'marcia',
    price: '$9.99',
    size: '2 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Got2b+Glued+Blasting+Freeze+Spray',
    imageUrl: 'https://mielleorganics.com/cdn/shop/files/Main-Images-Swatches-Edge-Gel_600x.jpg?v=1761166751',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition', 'growth'],
    tags: ['edge-control', 'rosemary', 'biotin', 'growth', 'strengthening'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 9.99,
  },
  {
    id: 'p-082',
    name: 'Glued Blasting Freeze Spray',
    brand: 'Got2b',
    category: 'edge-control',
    description: 'Extreme hold finishing spray with silicone-free formula.',
    whyItWorks: 'VP/VA copolymer creates an extreme-hold film that resists humidity and movement. Silicone-free so it won\'t build up on delicate edges. When your style is perfect and you need it to STAY — this spray freezes the moment.',
    recommendedBy: 'carmen',
    price: '$5.99',
    size: '12 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Naturalicious+Hello+Gorgeous+Rich+Hair+Butter',
    imageUrl: 'https://m.media-amazon.com/images/I/61EUt0rGwWL._SL500_.jpg',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition'],
    tags: ['freeze-spray', 'extreme-hold', 'finishing', 'silicone-free'],
    rating: 4.2,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 5.99,
  },
  {
    id: 'p-083',
    name: 'Hello Gorgeous Rich Hair Butter',
    brand: 'Naturalicious',
    category: 'edge-control',
    description: 'Avocado butter and JBCO sealant that locks moisture as the final step.',
    whyItWorks: 'Avocado butter penetrates deeper than shea due to its smaller molecular size. JBCO\'s ricinoleic acid strengthens while sealing. This butter is the last step — it seals everything in so your hair stays moisturized for days, not hours.',
    recommendedBy: 'ngozi',
    price: '$20.00',
    size: '4 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Oribe+Dry+Texturizing+Spray',
    imageUrl: 'https://naturalicious.net/cdn/shop/files/46788950-0646-42bc-b05c-d30784c720d3_32491a3e-3bc2-4fda-a48d-ad660f09fb59.png?v=1774886986',
    curlTypes: ['3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'definition'],
    tags: ['butter', 'avocado', 'JBCO', 'sealant', 'black-owned'],
    rating: 4.4,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 20.0,
  },
  {
    id: 'p-084',
    name: 'Dry Texturizing Spray',
    brand: 'Oribe',
    category: 'edge-control',
    description: 'Invisible lift and texture spray for wavy hair that needs body without crunch.',
    whyItWorks: 'Zeamays copolymer creates invisible volume at the roots without visible residue. Polymethylsilsesquioxane provides weightless texture. For wavy hair that needs body without crunch — this spray is invisible but the volume is not. Luxury finish.',
    recommendedBy: 'salma',
    price: '$49.00',
    size: '8.5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Mizani+25+Miracle+Milk+Leave-In+Treatment',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0738/6084/1787/files/400129-0.jpg',
    curlTypes: ['2a', '2b', '2c', '3a'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'simplify-routine'],
    tags: ['texture', 'volume', 'dry-spray', 'luxury', 'wavy'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 49.0,
  },
  {
    id: 'p-085',
    name: '25 Miracle Milk Leave-In Treatment',
    brand: 'Mizani',
    category: 'edge-control',
    description: 'Coconut, shea, and 25 benefits including heat protection, detangling, and anti-frizz.',
    whyItWorks: 'Twenty-five active benefits in one bottle: heat protection (ceramide-based shield), detangling (cationic surfactants reduce friction), anti-frizz (silicone barrier), UV protection, and more. For those who want the simplest routine possible.',
    recommendedBy: 'fatou',
    price: '$22.00',
    size: '8.5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Denman+Detangling+Brush',
    imageUrl: 'https://m.media-amazon.com/images/I/5132xde9izL._SL500_.jpg',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['simplify-routine', 'damage-repair', 'moisture'],
    tags: ['multi-benefit', 'heat-protection', 'detangle', 'all-in-one'],
    rating: 4.4,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 22.0,
  },

  // ── Tools & Accessories (5) ───────────────────────────────────
  {
    id: 'p-071',
    name: 'Denman-Style Brush (D3)',
    brand: 'Aunty Council',
    category: 'tool',
    description: '9-row styling brush that clumps curls into defined spirals. Brush through conditioner section by section.',
    whyItWorks: 'The 9-row pattern creates tension that clumps curls into defined spirals. Brush through conditioner section by section and watch your curl pattern pop.',
    recommendedBy: 'fatou',
    price: '$22.00',
    size: '7 Row',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/denman-brush.webp',
    curlTypes: ['3a', '3b', '3c', '4a'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition', 'simplify-routine'],
    tags: ['brush', 'detangle', 'define', 'styling', 'denman'],
    rating: 4.7,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 4,
    priceValue: 22.0,
  },
  {
    id: 'p-072',
    name: 'Silk Pillowcase (Queen)',
    brand: 'Aunty Council',
    category: 'accessory',
    description: 'Queen-size silk pillowcase for full coverage. Your hair stays protected all night, even for restless sleepers.',
    whyItWorks: 'Queen-size silk pillowcase means you never roll off the silk zone. Full coverage for restless sleepers — your hair stays protected all night.',
    recommendedBy: 'denise',
    price: '$42.00',
    size: 'Queen',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/silk-pillowcase-queen.webp',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['moisture', 'growth', 'simplify-routine'],
    tags: ['satin', 'pillowcase', 'sleep', 'protection', 'friction'],
    rating: 4.6,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 4,
    priceValue: 42.0,
  },
  {
    id: 'p-073',
    name: 'Universal Diffuser Attachment',
    brand: 'Aunty Council',
    category: 'tool',
    description: 'Deep-bowl diffuser that distributes airflow evenly. Dries curls in their natural formation without disrupting the pattern.',
    whyItWorks: 'Direct heat scatters curl clumps and creates frizz. A deep-bowl diffuser distributes airflow evenly, drying curls in their natural formation without disrupting the pattern.',
    recommendedBy: 'carmen',
    price: '$25.00',
    size: 'Universal Fit',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/universal-diffuser.webp',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition', 'simplify-routine'],
    tags: ['diffuser', 'tool', 'drying', 'frizz-free', 'devacurl'],
    rating: 4.5,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 25.0,
  },
  {
    id: 'p-074',
    name: 'Detangling Brush Set (3pc)',
    brand: 'Aunty Council',
    category: 'tool',
    description: 'Flexible-bristle detangling brushes that move with the curl pattern. Separates tangles from the ends up without ripping through knots.',
    whyItWorks: 'Rigid combs snap coily hair at the bend. Flexible bristles move with the curl pattern, separating tangles from the ends up without ripping through knots.',
    recommendedBy: 'fatou',
    price: '$26.00',
    size: 'One Size',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/detangling-brush-set.webp',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['simplify-routine'],
    tags: ['brush', 'detangle', 'flexible', 'gentle', 'breakage'],
    rating: 4.7,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 26.0,
  },
  {
    id: 'p-075',
    name: 'Microfiber Hair Towel (2-pack)',
    brand: 'Aunty Council',
    category: 'accessory',
    description: 'Microfiber towels that absorb water without friction. Dries 50% faster while keeping your curl pattern intact.',
    whyItWorks: 'Cotton terry cloth roughs up the hair cuticle, creating frizz on contact. Microfiber absorbs water without friction — dries 50% faster while keeping your curl pattern intact.',
    recommendedBy: 'denise',
    price: '$20.00',
    size: 'One Size',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/microfiber-hair-towel.webp',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition', 'simplify-routine', 'damage-repair'],
    tags: ['towel', 'microfiber', 'frizz-free', 'drying', 'budget'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 4,
    priceValue: 20.0,
  },

  // ── Wave & fine / low-porosity additions ──────────────────────
  {
    id: 'p-101',
    name: 'I Create Lift Volumizing Foam',
    brand: 'Innersense',
    category: 'styler',
    description: 'Featherlight foam that builds root lift and soft, bouncy definition.',
    whyItWorks: 'A cloud-light foam that adds volume and flexible definition without coating fine, easily-weighed-down strands. We chose it for looser patterns that go flat under heavier creams and gels.',
    recommendedBy: 'fatou',
    price: '$28.00',
    size: '5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=EVOLVh+SmartVolume+Volumizing+Leave-In',
    imageUrl: 'https://innersensebeauty.com/cdn/shop/files/LiftRetail.jpg?v=1709164314',
    curlTypes: ['2a', '2b', '2c', '3a', '3b'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'simplify-routine'],
    tags: ['mousse', 'foam', 'volume', 'lightweight', 'fine-hair', 'silicone-free'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 28.0,
  },
  {
    id: 'p-102',
    name: 'SmartVolume Volumizing Leave-In',
    brand: 'EVOLVh',
    category: 'leave-in',
    description: 'Spray leave-in that hydrates and lifts without any heaviness.',
    whyItWorks: 'A water-light spray means you control exactly how much lands where, so fine and wavy hair gets slip and moisture without going limp. A favorite for volume-loving wash days.',
    recommendedBy: 'fatou',
    price: '$26.00',
    size: '8.5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=EVOLVh+SmartVolume+Volumizing+Leave-In',
    imageUrl: 'https://m.media-amazon.com/images/I/41JFNRK9zeL._SL500_.jpg',
    curlTypes: ['2a', '2b', '2c', '3a', '3b'],
    porosity: ['low', 'normal'],
    goals: ['moisture', 'definition'],
    tags: ['leave-in', 'spray', 'volume', 'lightweight', 'fine-hair'],
    rating: 4.5,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 26.0,
  },
  {
    id: 'p-103',
    name: 'Direct Leave-In Weightless Moisture',
    brand: 'Giovanni',
    category: 'leave-in',
    description: 'Creamy, protein-free leave-in that softens without buildup.',
    whyItWorks: 'Protein-free and lightweight, so it hydrates and detangles waves and loose curls without the residue that heavier leave-ins leave on fine hair. Big slip for a small price.',
    recommendedBy: 'ngozi',
    price: '$7.99',
    size: '8.5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Giovanni+Direct+Leave-In+Weightless+Moisture',
    imageUrl: 'https://m.media-amazon.com/images/I/318ADsvxQYL._SL500_.jpg',
    curlTypes: ['2a', '2b', '2c', '3a'],
    porosity: ['low', 'normal'],
    goals: ['moisture', 'simplify-routine'],
    tags: ['leave-in', 'protein-free', 'lightweight', 'budget', 'detangling'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 7.99,
  },
  {
    id: 'p-104',
    name: 'Curl Talk Defining Gel Custard',
    brand: "Not Your Mother's",
    category: 'gel',
    description: 'Firm-hold, flake-free custard that elongates and defines curls.',
    whyItWorks: 'A silicone-free, protein-free custard that gives a long-lasting firm hold without crunch or flakes — built for coily-to-tighter textures that need definition that actually lasts.',
    recommendedBy: 'carmen',
    price: '$13.49',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Bounce+Curl+Defining+Butta',
    imageUrl: 'https://notyourmothers.com/cdn/shop/files/13180_NYM_CurlTalk_Custard_1_1200x1200.jpg?v=1695067709',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['definition'],
    tags: ['gel', 'custard', 'firm-hold', 'flake-free', 'silicone-free', 'budget'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 13.49,
  },
  {
    id: 'p-105',
    name: 'Defining Butta',
    brand: 'Bounce Curl',
    category: 'cream',
    description: 'Rich butter cream with murumuru and mango for hydrated definition.',
    whyItWorks: 'Murumuru, mango, and shea butters give thick, thirsty coils deep moisture and a soft, flexible hold — ideal for twist-outs and wash-and-gos that need to stay defined for days.',
    recommendedBy: 'denise',
    price: '$24.00',
    size: '8.4 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Kurlee+Belle+Kurl+Defining+Creme',
    imageUrl: 'https://www.bouncecurl.com/cdn/shop/files/defining-butta-pdp-main_699803ce-6924-4eb2-ab4f-ddd85efa89dc_1200x1200.png?v=1769509747',
    curlTypes: ['3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'definition'],
    tags: ['cream', 'butter', 'twist-out', 'wash-and-go', 'coily'],
    rating: 4.7,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 24.0,
  },
  {
    id: 'p-106',
    name: 'Kurl Defining Creme',
    brand: 'Kurlee Belle',
    category: 'cream',
    description: 'Tropical-oil curl cream made for the moisture needs of 4C hair.',
    whyItWorks: 'Shea butter and tropical oils deliver the deep, long-lasting moisture tightly coiled hair craves, defining without leaving a crunchy or stiff finish. Chosen for textures that shrink and dry out fast.',
    recommendedBy: 'carmen',
    price: '$20.00',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Kurlee+Belle+Kurl+Defining+Creme',
    imageUrl: 'https://m.media-amazon.com/images/I/51JK4+DdqdL._SL500_.jpg',
    curlTypes: ['4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'definition'],
    tags: ['cream', 'shea', '4c', 'twist-out', 'shingling'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 20.0,
  },
  {
    id: 'p-107',
    name: 'Pomegranate & Honey Coil Sculpting Custard',
    brand: 'Mielle Organics',
    category: 'gel',
    description: 'Thick custard that hydrates and shapes tight curls with deep definition.',
    whyItWorks: 'Coconut and babassu oils plus honey lock moisture into thirsty Type 4 coils while the custard sculpts deep, flexible definition with no crunch or flaking. Made specifically for tighter textures.',
    recommendedBy: 'carmen',
    price: '$11.99',
    size: '12 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Mielle+Organics+Pomegranate+%26+Honey+Coil+Sculpting+Custard',
    imageUrl: 'https://mielleorganics.com/cdn/shop/files/Packshot_99e45861-40d5-48fe-941d-27b2250c6979_600x.jpg?v=1761168994',
    curlTypes: ['3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['definition', 'moisture'],
    tags: ['custard', 'gel', 'coily', 'honey', 'flake-free', 'budget'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 11.99,
  },
  {
    id: 'p-108',
    name: 'A Curl Can Dream Moisturizing Cream',
    brand: 'Matrix',
    category: 'cream',
    description: 'One-step manuka honey cream that defines coils and protects from heat.',
    whyItWorks: 'Manuka honey wraps coils and kinks in lasting moisture while shielding against heat up to 450F — defining without stiffness whether you air-dry, diffuse, or set. A versatile multitasker.',
    recommendedBy: 'ngozi',
    price: '$22.00',
    size: '6.7 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Rizos+Curls+Defining+Custard',
    imageUrl: 'https://m.media-amazon.com/images/I/61xStImK3FL._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'definition', 'damage-repair'],
    tags: ['cream', 'manuka-honey', 'heat-protect', 'coily', 'definition'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 22.0,
  },
  {
    id: 'p-109',
    name: 'Defining Custard',
    brand: 'Rizos Curls',
    category: 'gel',
    description: 'Award-winning cream-gel custard with high slip for shiny, defined curls.',
    whyItWorks: 'A 2-in-1 cream-gel with mango butter and aloe gives high slip for easy shaping and a medium flexible hold — bouncy, shiny, frizz-controlled definition. Named Best Curl Definer at the 2025 People Beauty Awards.',
    recommendedBy: 'carmen',
    price: '$26.00',
    size: '9.46 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Rizos+Curls+Defining+Custard',
    imageUrl: 'https://rizoscurls.com/cdn/shop/files/Custard_b0d17328-8a6a-4d25-abe0-6238e3812de7.png?v=1764377805&width=1024',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['definition', 'moisture'],
    tags: ['custard', 'cream-gel', 'award-winner', 'high-slip', 'silicone-free'],
    rating: 4.7,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 26.0,
  },
  {
    id: 'p-110',
    name: 'Guava Hydrating Leave-In',
    brand: 'Ceremonia',
    category: 'leave-in',
    description: 'Lightweight leave-in that smooths the cuticle without greasy residue.',
    whyItWorks: 'Guava extract and blue agave deliver lightweight moisture that absorbs into the strand instead of sitting on top — ideal for low-porosity hair that buildup-prone heavier leave-ins weigh down. An Allure Best of Beauty pick.',
    recommendedBy: 'ngozi',
    price: '$24.00',
    size: '7.7 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Ceremonia+Guava+Hydrating+Leave-In',
    imageUrl: 'https://ceremonia.com/cdn/shop/products/Ceremonia_ECOMM_LeaveIn_4x5_aa8036d8-df8b-41c2-b792-41e2a9c259c2.jpg?v=1762440119',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['moisture', 'definition'],
    tags: ['leave-in', 'low-porosity', 'lightweight', 'award-winner', 'latinx-owned'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 24.0,
  },
  {
    id: 'p-111',
    name: 'Curl Quencher Moisturizing Conditioner',
    brand: 'Ouidad',
    category: 'conditioner',
    description: 'Glycerin-rich conditioner that helps resistant strands absorb moisture.',
    whyItWorks: 'Glycerin and panthenol are humectants that help low-porosity strands draw in moisture instead of repelling it, softening and adding slip without greasy buildup. Gentle enough for frequent use.',
    recommendedBy: 'ngozi',
    price: '$28.00',
    size: '8.5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Ouidad+Curl+Quencher+Moisturizing+Conditioner',
    imageUrl: 'https://www.ouidad.com/cdn/shop/files/CQ_Conditioner_1_Hero-Desktop-compressed.png?v=1753671871',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['moisture'],
    tags: ['conditioner', 'low-porosity', 'humectant', 'glycerin', 'slip'],
    rating: 4.4,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 1,
    priceValue: 28.0,
  },
  {
    id: 'p-112',
    name: 'Algae Renew Deep Conditioner',
    brand: 'Camille Rose',
    category: 'deep-conditioner',
    description: 'Protein-free deep conditioner for intense, softening hydration.',
    whyItWorks: 'A protein-free, humectant-forward mask for hair that gets stiff or straw-like from too much protein — pure moisture and slip to soften and restore elasticity. A go-to for moisture-overload-sensitive curls.',
    recommendedBy: 'salma',
    price: '$25.00',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Camille+Rose+Algae+Renew+Deep+Conditioner',
    imageUrl: 'https://m.media-amazon.com/images/I/31h-rawdi+L._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture'],
    tags: ['deep-conditioner', 'protein-free', 'hydration', 'black-owned'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 1,
    priceValue: 25.0,
  },
  {
    id: 'p-113',
    name: 'Coconut CoWash Cleansing Conditioner',
    brand: 'As I Am',
    category: 'cleanser',
    description: 'Cult-favorite co-wash that cleanses gently while moisturizing.',
    whyItWorks: 'A sulfate-free cleansing conditioner that refreshes the scalp and strands without stripping — coconut oil and saw palmetto keep curls soft and hydrated between full washes. A budget staple for textured hair.',
    recommendedBy: 'ngozi',
    price: '$9.49',
    size: '16 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=As+I+Am+Coconut+CoWash+Cleansing+Conditioner',
    imageUrl: 'https://m.media-amazon.com/images/I/61hoJnDgBWL._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'simplify-routine'],
    tags: ['co-wash', 'sulfate-free', 'coconut', 'budget', 'black-owned'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 1,
    priceValue: 9.49,
  },
  {
    id: 'p-114',
    name: 'Come Clean Clarifying Shampoo',
    brand: 'Kinky-Curly',
    category: 'cleanser',
    description: 'Gentle clarifying wash that lifts buildup without stripping.',
    whyItWorks: 'Sea kelp and mandarin orange clarify away product and mineral buildup — especially helpful for low-porosity hair where buildup blocks moisture from getting in. A periodic reset that does not over-dry.',
    recommendedBy: 'marcia',
    price: '$14.00',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Kinky-Curly+Come+Clean+Clarifying+Shampoo',
    imageUrl: 'https://m.media-amazon.com/images/I/41fi3660naL._SL500_.jpg',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal'],
    goals: ['scalp-health', 'simplify-routine'],
    tags: ['clarifying', 'buildup', 'low-porosity', 'gentle'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 1,
    priceValue: 14.0,
  },
  {
    id: 'p-115',
    name: 'Light Creme Gel',
    brand: 'Bounce Curl',
    category: 'gel',
    description: 'Cream-gel hybrid that defines fine curls with soft, weightless hold.',
    whyItWorks: 'A lighter cream-gel that defines and controls frizz on fine or loose curls without the heaviness of a butter or the crunch of a hard gel. The middle ground for hair that hates extremes.',
    recommendedBy: 'fatou',
    price: '$25.00',
    size: '8.5 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Bounce+Curl+Light+Creme+Gel',
    imageUrl: 'https://m.media-amazon.com/images/I/51PTUMKxNFL._SL500_.jpg',
    curlTypes: ['2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['definition'],
    tags: ['cream-gel', 'lightweight', 'fine-hair', 'frizz-control', 'definition'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 25.0,
  },
  {
    id: 'p-116',
    name: 'Coconut & Hibiscus Curl Enhancing Smoothie',
    brand: 'SheaMoisture',
    category: 'cream',
    description: 'Classic curl cream that defines and smooths with shea and silk protein.',
    whyItWorks: 'Shea butter, coconut oil, and silk protein define curls while taming frizz at a drugstore price — a longtime staple that gives medium-to-thick curls soft, moisturized hold.',
    recommendedBy: 'carmen',
    price: '$12.99',
    size: '12 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=SheaMoisture+Keratin+%26+Green+Tea+Restructurizer',
    imageUrl: 'https://m.media-amazon.com/images/I/717VqelOLNL._SL500_.jpg',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['definition', 'moisture'],
    tags: ['cream', 'shea', 'classic', 'budget', 'frizz-control'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 12.99,
  },
  {
    id: 'p-117',
    name: 'Keratin & Green Tea Restructurizer',
    brand: 'ApHogee',
    category: 'protein-treatment',
    description: 'Light leave-in protein spray for between heavy treatments.',
    whyItWorks: 'A light, spray-on keratin that adds everyday strength and slip without the intensity of a hard protein treatment — easy to control so even protein-sensitive and low-porosity hair can use it sparingly.',
    recommendedBy: 'amara',
    price: '$9.99',
    size: '8 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=TGIN+Green+Tea+Super+Moist+Leave-In',
    imageUrl: 'https://aphogee.com/cdn/shop/files/KeratinGreenTeaRest.jpg?v=1750195424',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['damage-repair'],
    tags: ['protein', 'spray', 'lightweight', 'keratin', 'budget'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 9.99,
  },
  {
    id: 'p-118',
    name: 'Green Tea Super Moist Leave-In',
    brand: 'TGIN',
    category: 'leave-in',
    description: 'Daily leave-in that softens and detangles with green tea and slip.',
    whyItWorks: 'Green tea, shea, and argan give curls daily softness and detangling slip without heaviness — a reliable, affordable everyday leave-in for medium-to-coily textures.',
    recommendedBy: 'ngozi',
    price: '$12.99',
    size: '13 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Camille+Rose+Almond+Jai+Twisting+Butter',
    imageUrl: 'https://tginatural.com/cdn/shop/files/GREEN-TEA-EDIT-2.png?v=1743539541&width=1024',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture'],
    tags: ['leave-in', 'detangling', 'budget', 'black-owned', 'daily'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 12.99,
  },
  {
    id: 'p-119',
    name: 'Almond Jai Twisting Butter',
    brand: 'Camille Rose',
    category: 'cream',
    description: 'Whipped butter for defined, moisturized twist-outs and braid-outs.',
    whyItWorks: 'A whipped almond-and-shea butter that gives twist-outs and braid-outs deep moisture and long-lasting, soft definition — built for set styles on coily hair that needs to hold for days.',
    recommendedBy: 'denise',
    price: '$19.99',
    size: '9 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Innersense+Hydrating+Cream+Hairbath',
    imageUrl: 'https://www.camillerose.com/cdn/shop/files/ProductCard_Signature_AlmondJai.webp?v=1772792913',
    curlTypes: ['3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['definition', 'moisture'],
    tags: ['butter', 'twist-out', 'braid-out', 'coily', 'black-owned'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 19.99,
  },
  {
    id: 'p-120',
    name: 'Hydrating Cream Hairbath',
    brand: 'Innersense',
    category: 'cleanser',
    description: 'Low-lather cream cleanser that washes gently without stripping.',
    whyItWorks: 'A creamy, low-lather cleanser with shea and rice protein that cleans while leaving moisture behind — gentle and lightweight enough for low-porosity and wavy hair that harsher shampoos leave dry.',
    recommendedBy: 'salma',
    price: '$28.00',
    size: '10 oz',
    affiliateUrl: 'https://www.amazon.com/s?k=Innersense+Hydrating+Cream+Hairbath',
    imageUrl: 'https://innersensebeauty.com/cdn/shop/files/HydratingCreamHairbathRetail.jpg?v=1709161327',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['moisture', 'simplify-routine'],
    tags: ['cleanser', 'low-lather', 'gentle', 'low-porosity', 'clean-beauty'],
    rating: 4.5,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 1,
    priceValue: 28.0,
  },

  // ── Aunty Council Store Products ──────────────────────────────
  // Products sold directly on auntycurlcouncil.com
  {
    id: 'p-201',
    name: 'Satin Bonnet (Standard)',
    brand: 'Aunty Council',
    category: 'accessory',
    description: 'Double-lined satin bonnet that protects your curls overnight. Eliminates friction and moisture loss from cotton pillowcases.',
    whyItWorks: 'Cotton absorbs moisture and creates friction that breaks curls overnight. Double-lined satin eliminates both — you wake up with day-one definition instead of frizz.',
    recommendedBy: 'denise',
    price: '$18.00',
    size: 'Standard',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/satin-bonnet.webp',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['moisture', 'definition', 'simplify-routine'],
    tags: ['bonnet', 'satin', 'sleep', 'protection', 'overnight', 'aunty-council'],
    rating: 4.8,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 4,
    priceValue: 18.0,
  },
  {
    id: 'p-202',
    name: 'Satin Bonnet (XL)',
    brand: 'Aunty Council',
    category: 'accessory',
    description: 'XL deep-crown satin bonnet for thick hair, locs, and voluminous styles. Holds your full volume without squeezing.',
    whyItWorks: 'Standard bonnets compress thick hair and locs, creating flat spots and frizz. The XL deep crown holds your full volume without squeezing — wake up with your style intact.',
    recommendedBy: 'ngozi',
    price: '$22.00',
    size: 'XL',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/satin-bonnet-xl.webp',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['moisture', 'definition', 'simplify-routine'],
    tags: ['bonnet', 'satin', 'XL', 'locs', 'thick-hair', 'sleep', 'aunty-council'],
    rating: 4.8,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 22.0,
  },
  {
    id: 'p-203',
    name: 'Silk Pillowcase (Standard)',
    brand: 'Aunty Council',
    category: 'accessory',
    description: 'Mulberry silk pillowcase that reduces friction by 43% vs cotton. Less breakage, less frizz, fewer sleep creases.',
    whyItWorks: 'Silk reduces friction by 43% compared to cotton. Less friction means less breakage, less frizz, and fewer sleep creases. Your night routine becomes automatic.',
    recommendedBy: 'salma',
    price: '$35.00',
    size: 'Standard',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/silk-pillowcase.webp',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['moisture', 'definition', 'damage-repair', 'simplify-routine'],
    tags: ['pillowcase', 'silk', 'sleep', 'protection', 'anti-frizz', 'aunty-council'],
    rating: 4.7,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 35.0,
  },
  {
    id: 'p-204',
    name: 'Wide-Tooth Detangling Comb',
    brand: 'Aunty Council',
    category: 'tool',
    description: 'Seamless wide-tooth comb for wet detangling. No micro-seams that catch and snap curly hair.',
    whyItWorks: 'Injection-molded combs have micro-seams that catch and snap curly hair. Seamless wide-tooth combs glide through without snagging — essential for wet detangling.',
    recommendedBy: 'marcia',
    price: '$12.00',
    size: 'One Size',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/wide-tooth-comb.webp',
    curlTypes: ['2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['simplify-routine', 'damage-repair'],
    tags: ['comb', 'detangling', 'wide-tooth', 'wash-day', 'aunty-council'],
    rating: 4.6,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 4,
    priceValue: 12.0,
  },
  {
    id: 'p-205',
    name: 'Electric Scalp Massager',
    brand: 'Aunty Council',
    category: 'tool',
    description: 'Waterproof electric scalp massager that stimulates blood flow to follicles during shampoo. Product distribution and stimulation in one step.',
    whyItWorks: 'Electric vibration increases blood flow to hair follicles more consistently than manual massage. Waterproof design means you can use it during shampoo — product distribution and stimulation in one step.',
    recommendedBy: 'marcia',
    price: '$32.00',
    size: 'One Size',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/electric-scalp-massager.webp',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['growth', 'scalp-health'],
    tags: ['scalp', 'massager', 'electric', 'growth', 'blood-flow', 'aunty-council'],
    rating: 4.7,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 32.0,
  },
  {
    id: 'p-206',
    name: 'Mini Portable Hair Steamer',
    brand: 'Aunty Council',
    category: 'tool',
    description: 'Nano-ionic portable hair steamer for deep conditioning at home. Opens the cuticle so treatments actually penetrate.',
    whyItWorks: 'Steam opens the hair cuticle so deep conditioner actually penetrates instead of sitting on top. Nano-ionic mist breaks water into smaller particles for deeper moisture infusion.',
    recommendedBy: 'ngozi',
    price: '$58.00',
    size: 'Portable',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/portable-hair-steamer.webp',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['moisture', 'damage-repair'],
    tags: ['steamer', 'deep-conditioning', 'moisture', 'treatment', 'aunty-council'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 58.0,
  },
  {
    id: 'p-207',
    name: 'Flexi Rods Set (50pc)',
    brand: 'Aunty Council',
    category: 'tool',
    description: 'Mixed-size flexi rods for heatless curls overnight. Different sizes give you spirals, waves, or ringlets on demand.',
    whyItWorks: 'Heat styling damages the protein bonds in curly hair. Flexi rods create defined curls overnight without any heat — different sizes give you spirals, waves, or ringlets on demand.',
    recommendedBy: 'carmen',
    price: '$20.00',
    size: '50 rods, mixed sizes',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/flexi-rods-set.webp',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition', 'damage-repair', 'simplify-routine'],
    tags: ['flexi-rods', 'heatless', 'curls', 'styling', 'overnight', 'aunty-council'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 20.0,
  },
  {
    id: 'p-208',
    name: 'Manual Scalp Massager (2-pack)',
    brand: 'Aunty Council',
    category: 'tool',
    description: 'Silicone scalp massager that increases blood flow to follicles. Pairs with scalp oil to boost absorption and lift buildup.',
    whyItWorks: 'Increases blood flow to the follicle by up to 300% during use. Pairs with your scalp oil to boost absorption. The bristles lift product buildup that blocks growth.',
    recommendedBy: 'marcia',
    price: '$14.00',
    size: '2-pack',
    affiliateUrl: 'https://auntycurlcouncil.com/products',
    imageUrl: 'https://auntycurlcouncil.com/products/scalp-massager.webp',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['growth', 'scalp-health'],
    tags: ['scalp', 'massager', 'manual', 'growth', 'exfoliate', 'aunty-council'],
    rating: 4.6,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 4,
    priceValue: 14.0,
  },
];
