/**
 * Product Database — Curated textured hair products.
 *
 * Each product is tagged with hair properties it works best for,
 * which aunty recommends it, and affiliate potential.
 * This is the monetization engine of the app.
 */

import type { AuntyId } from './aunties';
import type { CurlType, Porosity, PrimaryGoal } from '../types';

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: ProductCategory;
  description: string;
  whyItWorks: string; // ingredient science — why this was chosen for their hair
  recommendedBy: AuntyId; // which aunty endorses it
  price: string; // display price
  size: string;
  imageUrl?: string;
  affiliateUrl?: string;

  // Matching criteria
  curlTypes: CurlType[]; // which curl types benefit
  porosity: Porosity[]; // which porosity levels
  goals: PrimaryGoal[]; // which goals it serves
  tags: string[]; // searchable tags

  // Display
  rating: number; // 1-5
  isPremiumPick: boolean;
  isBudgetFriendly: boolean;
  scopeTier: 1 | 2 | 3 | 4;
  priceValue: number;
}

export type ProductCategory =
  | 'cleanser'
  | 'conditioner'
  | 'deep-conditioner'
  | 'leave-in'
  | 'styler'
  | 'oil'
  | 'gel'
  | 'cream'
  | 'protein-treatment'
  | 'scalp-treatment'
  | 'tool'
  | 'accessory';

export const CATEGORY_LABELS: Record<ProductCategory, string> = {
  cleanser: 'Cleansers',
  conditioner: 'Conditioners',
  'deep-conditioner': 'Deep Conditioners',
  'leave-in': 'Leave-Ins',
  styler: 'Stylers',
  oil: 'Oils & Serums',
  gel: 'Gels',
  cream: 'Creams & Butters',
  'protein-treatment': 'Protein Treatments',
  'scalp-treatment': 'Scalp Treatments',
  tool: 'Tools',
  accessory: 'Accessories',
};

// ─── Product Catalog ─────────────────────────────────────────────

export const PRODUCTS: Product[] = [
  // ── Cleansers ──────────────────────────────────────────────────
  {
    id: 'p-001',
    name: 'Hydrating Cream Cleanser',
    brand: 'SheaMoisture',
    category: 'cleanser',
    description: 'Coconut & Hibiscus co-wash that cleanses without stripping moisture.',
    whyItWorks: 'Sulfate-free so it won\'t strip your natural oils. The coconut oil in this penetrates the hair shaft — one of the only oils that actually does. That\'s why we picked it for your texture.',
    recommendedBy: 'ngozi',
    price: '$11.99',
    size: '13 oz',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'simplify-routine'],
    tags: ['co-wash', 'sulfate-free', 'moisturizing', 'coconut'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 1,
    priceValue: 11.99,
  },
  {
    id: 'p-002',
    name: 'Apple Cider Vinegar Clarifying Shampoo',
    brand: 'dpHUE',
    category: 'cleanser',
    description: 'Gentle clarifying shampoo that removes buildup without over-drying.',
    whyItWorks: 'ACV restores your scalp\'s pH to 4.5-5.5 where textured hair thrives. Removes silicone and mineral buildup without the sulfate damage. We chose this because your curl pattern needs a clean slate without the strip.',
    recommendedBy: 'fatou',
    price: '$35.00',
    size: '8.5 oz',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'scalp-health'],
    tags: ['clarifying', 'ACV', 'buildup', 'gentle'],
    rating: 4.3,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 1,
    priceValue: 35.0,
  },
  {
    id: 'p-003',
    name: 'Black Soap Shampoo',
    brand: 'SheaMoisture',
    category: 'cleanser',
    description: 'African Black Soap deep cleansing shampoo for scalp health.',
    whyItWorks: 'African black soap contains plantain ash and shea — natural antibacterials that clear scalp inflammation without drying your strands. Selected because textured hair needs scalp health as a growth foundation.',
    recommendedBy: 'marcia',
    price: '$10.99',
    size: '13 oz',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['scalp-health', 'damage-repair'],
    tags: ['scalp', 'clarifying', 'african-black-soap', 'deep-clean'],
    rating: 4.2,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 1,
    priceValue: 10.99,
  },

  // ── Deep Conditioners ──────────────────────────────────────────
  {
    id: 'p-010',
    name: 'Honey & Virgin Coconut Oil Deep Conditioner',
    brand: 'Mielle Organics',
    category: 'deep-conditioner',
    description: 'Intense moisture treatment with honey and coconut oil for dry, damaged curls.',
    whyItWorks: 'Honey is a natural humectant — it pulls moisture from the air into your strand. Combined with coconut oil that penetrates the cortex, this treats both the surface and interior of your hair. Chosen for high-porosity textures that lose moisture fast.',
    recommendedBy: 'ngozi',
    price: '$12.99',
    size: '12 oz',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'damage-repair'],
    tags: ['deep-condition', 'honey', 'coconut', 'moisture', 'repair'],
    rating: 4.7,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 12.99,
  },
  {
    id: 'p-011',
    name: 'Cholesterol Hair Conditioning Cream',
    brand: 'Queen Helene',
    category: 'deep-conditioner',
    description: 'Classic deep conditioner that softens and strengthens textured hair.',
    whyItWorks: 'Cholesterol-based conditioners mimic your hair\'s natural lipid layer — they fill gaps in damaged cuticles. This formula softens without protein overload, making it safe for weekly use on textured hair.',
    recommendedBy: 'denise',
    price: '$6.99',
    size: '15 oz',
    curlTypes: ['3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'damage-repair', 'simplify-routine'],
    tags: ['deep-condition', 'classic', 'softening', 'budget'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 2,
    priceValue: 6.99,
  },
  {
    id: 'p-012',
    name: 'Babassu Deep Treatment Masque',
    brand: 'Mielle Organics',
    category: 'deep-conditioner',
    description: 'Protein and moisture balancing mask with babassu and mint.',
    whyItWorks: 'Babassu oil has a molecular structure similar to coconut but lighter — absorbs faster into fine-textured curls. The mint stimulates scalp circulation. Picked because your hair needs protein-moisture balance without heaviness.',
    recommendedBy: 'amara',
    price: '$13.99',
    size: '8 oz',
    curlTypes: ['3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['damage-repair', 'growth', 'moisture'],
    tags: ['protein', 'moisture', 'balance', 'mask', 'mint'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 13.99,
  },

  // ── Leave-Ins ──────────────────────────────────────────────────
  {
    id: 'p-020',
    name: 'Knot Today Leave-In Conditioner',
    brand: 'Kinky-Curly',
    category: 'leave-in',
    description: 'Lightweight detangling leave-in that defines without weighing down.',
    whyItWorks: 'Organic marshmallow root extract creates slip at the molecular level — reduces friction between strands by 60%. No silicones. Selected because textured hair needs detangling without breakage.',
    recommendedBy: 'fatou',
    price: '$14.99',
    size: '8 oz',
    curlTypes: ['3a', '3b', '3c', '4a'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'simplify-routine'],
    tags: ['leave-in', 'detangle', 'lightweight', 'slip'],
    rating: 4.5,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 14.99,
  },
  {
    id: 'p-021',
    name: 'Quench Leave-In Conditioning Cream',
    brand: 'Aunt Jackie\'s',
    category: 'leave-in',
    description: 'Rich moisture leave-in for thick, coily hair that needs extra hydration.',
    whyItWorks: 'Shea butter and olive oil are heavy emollients that coat high-porosity strands and slow moisture loss. This stays on coily hair where lighter leave-ins evaporate in hours.',
    recommendedBy: 'ngozi',
    price: '$8.99',
    size: '12 oz',
    curlTypes: ['4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['moisture', 'growth'],
    tags: ['leave-in', 'cream', 'moisture', 'thick-hair', 'coily'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 8.99,
  },

  // ── Stylers & Gels ─────────────────────────────────────────────
  {
    id: 'p-030',
    name: 'Curling Custard',
    brand: 'Kinky-Curly',
    category: 'gel',
    description: 'Organic gel that defines curls with zero crunch or flaking.',
    whyItWorks: 'Organic aloe and agave create a flexible cast that defines without crunch. No polyquats or PVP that cause flaking on textured hair. Chosen because your curl pattern needs hold that moves.',
    recommendedBy: 'carmen',
    price: '$17.99',
    size: '8 oz',
    curlTypes: ['3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['definition', 'simplify-routine'],
    tags: ['gel', 'definition', 'organic', 'no-crunch', 'wash-and-go'],
    rating: 4.6,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 17.99,
  },
  {
    id: 'p-031',
    name: 'Flaxseed Gel',
    brand: 'Aunt Jackie\'s',
    category: 'gel',
    description: 'Natural flaxseed gel for soft hold and curl definition.',
    whyItWorks: 'Flaxseed mucilage is a natural polymer — it forms a gel film that defines curls while adding omega-3 fatty acids that strengthen the strand. No synthetic hold agents. Works across all porosity levels.',
    recommendedBy: 'carmen',
    price: '$8.99',
    size: '15 oz',
    curlTypes: ['2c', '3a', '3b', '3c', '4a'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition', 'simplify-routine'],
    tags: ['gel', 'flaxseed', 'natural', 'soft-hold', 'definition'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 8.99,
  },
  {
    id: 'p-032',
    name: 'Twist Defining Cream',
    brand: 'Cantu',
    category: 'cream',
    description: 'Shea butter cream for twist-outs and braid-outs with lasting moisture.',
    whyItWorks: 'Shea butter\'s stearic acid fills gaps in the cuticle, reducing frizz and locking twist definition for 3-5 days. We chose this for coily patterns that need a cream heavy enough to hold a set.',
    recommendedBy: 'denise',
    price: '$5.99',
    size: '12 oz',
    curlTypes: ['3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['definition', 'moisture'],
    tags: ['cream', 'twist-out', 'shea-butter', 'protective-style'],
    rating: 4.3,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 5.99,
  },

  // ── Oils ───────────────────────────────────────────────────────
  {
    id: 'p-040',
    name: 'Jamaican Black Castor Oil',
    brand: 'Tropic Isle Living',
    category: 'oil',
    description: 'Pure JBCO for scalp massage, edges, and growth stimulation.',
    whyItWorks: 'JBCO\'s ricinoleic acid increases blood flow to the scalp by up to 3x. The ash content raises pH to open follicles for deeper penetration. Selected as the #1 growth oil for textured hair based on ingredient analysis.',
    recommendedBy: 'marcia',
    price: '$9.99',
    size: '4 oz',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['growth', 'scalp-health', 'damage-repair'],
    tags: ['oil', 'JBCO', 'growth', 'scalp', 'edges', 'massage'],
    rating: 4.8,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 9.99,
  },
  {
    id: 'p-041',
    name: 'Pure Argan Oil',
    brand: 'Josie Maran',
    category: 'oil',
    description: 'Lightweight argan oil that seals moisture and adds shine without weight.',
    whyItWorks: 'Argan is 80% unsaturated fatty acids — it penetrates without coating. Vitamin E repairs oxidative damage. Chosen for low-porosity hair because it\'s light enough to absorb where heavier oils can\'t.',
    recommendedBy: 'salma',
    price: '$49.00',
    size: '1.7 oz',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c'],
    porosity: ['low', 'normal'],
    goals: ['moisture', 'definition', 'simplify-routine'],
    tags: ['oil', 'argan', 'lightweight', 'shine', 'sealing', 'moroccan'],
    rating: 4.7,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 3,
    priceValue: 49.0,
  },
  {
    id: 'p-042',
    name: 'Rosemary Mint Scalp Oil',
    brand: 'Mielle Organics',
    category: 'oil',
    description: 'Stimulating scalp oil with rosemary and biotin for growth.',
    whyItWorks: 'Rosemary oil matched minoxidil in a 6-month clinical study for hair growth. Biotin strengthens keratin bonds. This targets the two proven growth pathways — circulation and structural protein.',
    recommendedBy: 'marcia',
    price: '$9.99',
    size: '2 oz',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['growth', 'scalp-health'],
    tags: ['oil', 'rosemary', 'mint', 'growth', 'scalp', 'stimulating'],
    rating: 4.8,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 3,
    priceValue: 9.99,
  },

  // ── Protein Treatments ─────────────────────────────────────────
  {
    id: 'p-050',
    name: 'Aphogee Two Step Protein Treatment',
    brand: 'Aphogee',
    category: 'protein-treatment',
    description: 'Professional-strength protein treatment for severely damaged hair.',
    whyItWorks: 'Hydrolyzed keratin proteins are small enough to enter the cortex and rebuild internal bonds. This is the gold standard for structural repair — chosen when elasticity is compromised from heat or chemical damage.',
    recommendedBy: 'amara',
    price: '$14.99',
    size: '4 oz',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['normal', 'high'],
    goals: ['damage-repair', 'growth'],
    tags: ['protein', 'repair', 'professional', 'breakage', 'strength'],
    rating: 4.6,
    isPremiumPick: true,
    isBudgetFriendly: false,
    scopeTier: 2,
    priceValue: 14.99,
  },

  // ── Scalp Treatments ───────────────────────────────────────────
  {
    id: 'p-060',
    name: 'Tea Tree Scalp Treatment',
    brand: 'TGIN',
    category: 'scalp-treatment',
    description: 'Soothing tea tree and argan oil treatment for itchy, flaky scalps.',
    whyItWorks: 'Tea tree oil\'s terpinen-4-ol is antifungal and anti-inflammatory — targets the root cause of dandruff, not just symptoms. Argan soothes without clogging follicles. Selected for scalp conditions common in textured hair.',
    recommendedBy: 'salma',
    price: '$14.99',
    size: '4 oz',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['scalp-health'],
    tags: ['scalp', 'tea-tree', 'soothing', 'anti-itch', 'treatment'],
    rating: 4.4,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 14.99,
  },

  // ── Tools & Accessories ────────────────────────────────────────
  {
    id: 'p-070',
    name: 'Satin Bonnet',
    brand: 'GRACE ELEYAE',
    category: 'accessory',
    description: 'Adjustable satin-lined bonnet that protects your style overnight.',
    whyItWorks: 'Cotton absorbs 27x its weight in moisture — it literally drinks your hair products overnight. Satin creates zero friction, preserving curl definition and moisture. Non-negotiable for textured hair.',
    recommendedBy: 'denise',
    price: '$29.99',
    size: 'One Size',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['moisture', 'definition', 'growth', 'simplify-routine'],
    tags: ['satin', 'bonnet', 'sleep', 'protection', 'overnight'],
    rating: 4.8,
    isPremiumPick: false,
    isBudgetFriendly: false,
    scopeTier: 4,
    priceValue: 29.99,
  },
  {
    id: 'p-071',
    name: 'Detangling Brush',
    brand: 'Denman',
    category: 'tool',
    description: 'D3 styling brush that defines curls and distributes product evenly.',
    whyItWorks: 'The D3\'s nylon pin spacing is engineered for curl clumping — it separates strands just enough to form defined groups without disrupting the curl pattern. The standard tool for wash-and-go definition.',
    recommendedBy: 'fatou',
    price: '$14.99',
    size: '7 Row',
    curlTypes: ['3a', '3b', '3c', '4a'],
    porosity: ['low', 'normal', 'high'],
    goals: ['definition', 'simplify-routine'],
    tags: ['brush', 'detangle', 'define', 'styling', 'denman'],
    rating: 4.7,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 4,
    priceValue: 14.99,
  },
  {
    id: 'p-072',
    name: 'Satin Pillowcase',
    brand: 'Kitsch',
    category: 'accessory',
    description: 'Satin pillowcase that reduces friction and preserves moisture overnight.',
    whyItWorks: 'Insurance for your routine. Same zero-friction benefit as a bonnet but can\'t fall off. Reduces mechanical breakage from tossing and turning — the #1 cause of unexplained breakage in textured hair.',
    recommendedBy: 'denise',
    price: '$19.99',
    size: 'Standard',
    curlTypes: ['2a', '2b', '2c', '3a', '3b', '3c', '4a', '4b', '4c'],
    porosity: ['low', 'normal', 'high'],
    goals: ['moisture', 'growth', 'simplify-routine'],
    tags: ['satin', 'pillowcase', 'sleep', 'protection', 'friction'],
    rating: 4.6,
    isPremiumPick: false,
    isBudgetFriendly: true,
    scopeTier: 4,
    priceValue: 19.99,
  },
];
